# Generated by Django 6.0.2 on 2026-02-18 16:46

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('photo', models.ImageField(upload_to='design_requests/photos/', validators=[main.models.validate_image_size, main.models.validate_image_extension], verbose_name='Photo of the room / plan')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='design_requests/results/', verbose_name='Photo of the completed work')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Administrators comment')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('done', 'Done')], default='new', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Design request',
                'verbose_name_plural': 'Design requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
